# -*- coding: utf-8 -*-
"""Fraud detection project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtHLAgu2iDTWYiHTEbv15NrzAQ51Tsur
"""

# Step 1: Import all necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/transactions.csv')
df.head()
print(df.isnull().sum())



# Step 3: Plot class imbalance
sns.countplot(x=df["is_fraud"])
plt.title("Fraud vs Non-Fraud Count")
plt.show()

# Step 6: Drop unhelpful columns
drop_cols = ["transaction_id", "user_id", "transaction_time"]
df = df.drop(columns=drop_cols)

print(df.head())

# Step 7: Define features (X) and target (y)
X = df.drop(columns=["is_fraud"])
y = df["is_fraud"]

# Step 8: Identify numeric and categorical columns
numeric_features = [
    "account_age_days",
    "total_transactions_user",
    "avg_amount_user",
    "amount",
    "shipping_distance_km"
]

categorical_features = [
    "country",
    "bin_country",
    "channel",
    "merchant_category",
    "promo_used",
    "avs_match",
    "cvv_result",
    "three_ds_flag"
]

# Step 9: Scaler for numeric features
numeric_transformer = Pipeline(steps=[
    ("scaler", StandardScaler())
])

# Step 10: One-hot encoder for categorical features
categorical_transformer = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# Step 11: Combine both transformers
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# Step 12: Split the data (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Step 13: Fit-transform on training data, transform on test data
X_train_prep = preprocessor.fit_transform(X_train)
X_test_prep = preprocessor.transform(X_test)

# Step 14: Balance fraud data using SMOTE
sm = SMOTE(random_state=42)
X_train_bal, y_train_bal = sm.fit_resample(X_train_prep, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", y_train_bal.value_counts())

# Step 15: Train Logistic Regression
log_model = LogisticRegression(max_iter=2000)
log_model.fit(X_train_bal, y_train_bal)


# Step 17: Make predictions and evaluate Logistic Regression
y_pred_log = log_model.predict(X_test_prep)
accuracy_log = accuracy_score(y_test, y_pred_log)

print(f"Logistic Regression Accuracy: {accuracy_log:.4f}")
print("\nClassification Report (Logistic Regression):")
print(classification_report(y_test, y_pred_log))

# Optional: Confusion Matrix
cm_log = confusion_matrix(y_test, y_pred_log)
print("\nConfusion Matrix (Logistic Regression):\n", cm_log)

# Step 16: Train Random Forest
rf_model = RandomForestClassifier(n_estimators=300, random_state=42)
rf_model.fit(X_train_bal, y_train_bal)

# Step 17: Make predictions and evaluate Random Forest
y_pred_rf = rf_model.predict(X_test_prep)
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print(f"Random Forest Accuracy: {accuracy_rf:.4f}")
print("\nClassification Report (Random Forest):")
print(classification_report(y_test, y_pred_rf))

# Optional: Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix (Random Forest):\n", cm_rf)

# Step 18: Train SVM
from sklearn.svm import SVC
svm_model = SVC(kernel="rbf", probability=True)
svm_model.fit(X_train_bal, y_train_bal)